name: Build RevampedFMRadio APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with gradlew
        uses: actions/checkout@v4
        with:
          repository: BGCX067/RevampedFMRadio-apk-builder
          ref: main
          
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Make gradlew executable
        run: chmod +x gradlew
          
      - name: Build with Gradle
        run: ./gradlew assembleRelease
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RevampedFMRadio
          path: app/build/outputs/apk/release/*.apk
